[book]
authors = ["Mat Jones"]
language = "en"
multilingual = false
src = "docs"
title = "mjones.network"

[output.html]
theme = "mdbook-theme" # custom highlight.js with Nix language highlighting
default-theme = "Ayu"
preferred-dark-theme = "Ayu"
additional-css = ["./docs/custom.css"]
cname = "mjones.network"
site-url = "https://mjones.network"

[output.html.print]
enable = false

[preprocessor.ublock-mdbook]
command = "ublock-mdbook"
