docs: docs/
readme: README.md
hammerspoon: hammerspoon/
vim: nvim/
paths: config-paths.yml
ssh: home-manager/modules/ssh.nix
wezterm: wezterm/
home: home-manager/
git: home-manager/modules/git.nix
bat: home-manager/modules/bat.nix
starship: home-manager/modules/starship.nix
atuin: home-manager/modules/atuin.nix
