{
  pkgs,
  lib,
  isServer,
  ...
}:
{
  imports = [ (import ../nixos/nix-conf.nix { isHomeManager = false; }) ];
  i18n = {
    # for unicode input
    inputMethod = {
      type = "ibus";
      ibus.engines = [ pkgs.ibus-engines.m17n ];
    };

    # Select internationalisation properties.
    defaultLocale = "en_US.UTF-8";

    extraLocaleSettings = {
      LC_ADDRESS = "en_US.UTF-8";
      LC_IDENTIFICATION = "en_US.UTF-8";
      LC_MEASUREMENT = "en_US.UTF-8";
      LC_MONETARY = "en_US.UTF-8";
      LC_NAME = "en_US.UTF-8";
      LC_NUMERIC = "en_US.UTF-8";
      LC_PAPER = "en_US.UTF-8";
      LC_TELEPHONE = "en_US.UTF-8";
      LC_TIME = "en_US.UTF-8";
    };
  };
  environment = {
    variables = {
      PAGER = "less -FRX";
      NIXOS_OZONE_WL = "1";
    };
  };

  nix.optimise.automatic = true;

  security.rtkit.enable = true;
  networking = {
    wireguard.enable = true;
    firewall = {
      enable = true;
      allowPing = true;
    };
  };
  services = lib.mkMerge [
    {
      # enable mDNS for stuff like NAS and SSH
      avahi = {
        enable = true;
        nssmdns4 = true;
        openFirewall = true;
        publish = {
          enable = true;
          userServices = true;
        };
      };
    }
    (lib.mkIf (!isServer) {
      # going to use pipewire instead
      pulseaudio.enable = false;

      # Configure keymap in X11
      xserver = {
        xkb = {
          layout = "us";
          variant = "";
        };
      };

      # Enable CUPS to print documents.
      printing.enable = true;
      pipewire = {
        enable = true;
        alsa.enable = true;
        alsa.support32Bit = true;
        pulse.enable = true;
        # If you want to use JACK applications, uncomment this
        #jack.enable = true;

        # use the example session manager (no others are packaged yet so this is enabled by default,
        # no need to redefine it in your config for now)
        #media-session.enable = true;
      };
    })
  ];

  boot = {
    loader = {
      # bootloader
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };
  };

  systemd.settings.Manager.DefaultTimeoutStopSec = "10s";

  security = {
    sudo.enable = true;
    pam = {
      sshAgentAuth.enable = true;
      # sshAgentAuth.authorizedKeysFiles =
      #   lib.mkForce [ "/etc/ssh/authorized_keys.d/%u" ];
      services.sudo.sshAgentAuth = true;
    };
  };

  # Set your time zone.
  time.timeZone = "America/New_York";

  users = {
    mutableUsers = false;
    users = {
      mat = {
        shell = pkgs.fish;
        isNormalUser = true;
        # generated by `mkpasswd`
        hashedPassword = "$y$j9T$L.RrmE3CRSB.lQayiw2ZN/$vA4XkSR13yL016t3HaZ11uCN/sCmXqBcuUcSBxMjiPD";
        home = "/home/mat";
        extraGroups = [
          "wheel"
          "networkmanager"
          "oci"
          "podman"
        ];
      };
    };
  };
}
