return {
  name = 'OneDarkPro',
  colors = {
    ansi = {
      '#000000',
      '#ef596f',
      '#89ca78',
      '#e5c07b',
      '#61afef',
      '#d55fde',
      '#2bbac5',
      '#abb2bf',
    },
    background = '#000000',
    brights = {
      '#1a1a1a',
      '#f38897',
      '#a9d89d',
      '#edd4a6',
      '#8fc6f4',
      '#e089e7',
      '#4bced8',
      '#c8cdd5',
    },
    compose_cursor = '#a9d89d',
    cursor_bg = '#89ca78',
    cursor_border = '#89ca78',
    cursor_fg = '#000000',
    foreground = '#abb2bf',
    indexed = {
      ['16'] = '#e5c07b',
      ['17'] = '#abb2bf',
    },
    scrollbar_thumb = '#495162',
    selection_bg = '#495162',
    selection_fg = '#c8cdd5',
    split = '#c8cdd5',
    tab_bar = {
      active_tab = {
        bg_color = '#a9d89d',
        fg_color = '#000000',
        intensity = 'Normal',
        italic = false,
        strikethrough = false,
        underline = 'None',
      },
      background = '#495162',
      inactive_tab = {
        bg_color = '#abb2bf',
        fg_color = '#000000',
        intensity = 'Normal',
        italic = false,
        strikethrough = false,
        underline = 'None',
      },
      inactive_tab_edge = '#495162',
      inactive_tab_hover = {
        bg_color = '#000000',
        fg_color = '#abb2bf',
        intensity = 'Normal',
        italic = false,
        strikethrough = false,
        underline = 'None',
      },
      new_tab = {
        bg_color = '#495162',
        fg_color = '#abb2bf',
        intensity = 'Normal',
        italic = false,
        strikethrough = false,
        underline = 'None',
      },
      new_tab_hover = {
        bg_color = '#495162',
        fg_color = '#abb2bf',
        intensity = 'Normal',
        italic = false,
        strikethrough = false,
        underline = 'None',
      },
    },
    visual_bell = '#495162',
  },
}
