#! /bin/bash

touch _index.md
touch _index.es.md
touch _index.de.md
touch _index.fr.md
touch _index.jp.md
touch _index.ru.md
touch _index.it.md
touch _index.ko.md
touch _index.pt.md
touch _index.zh-cn.md
touch _index.zh-tw.md

