#!/usr/bin/env bash

if [[ "$#" -ne 2 ]]; then
    echo "Incorrect number of arguments.\n";
    echo "    Usage: dump-translations [source] [target]\number"
    echo "    example: dump-translations ./translations ./dumped\n"
    exit 1
fi

SOURCE_DIR=""
pushd "$1"
SOURCE_DIR="$(pwd)"
popd

TARGET_DIR=""
mkdir -p "$2"
pushd "$2"
TARGET_DIR="$(pwd)"
popd

# "safe-find": https://github.com/l0b0/tilde/blob/master/examples/safe-find.sh
while IFS= read -r -d '' -u 9
do
    FILENAME="$(basename $REPLY)"
    LOCAL_DIR_NAME="$(dirname $REPLY)"
    LANG=""

    if [[ "$LOCAL_DIR_NAME" == *"/de/"* ]]; then
        LANG="de"
    elif [[ "$LOCAL_DIR_NAME" == *"/es-ES/"* ]]; then
        LANG="es"
    elif [[ "$LOCAL_DIR_NAME" == *"/fr/"* ]]; then
        LANG="fr"
    elif [[ "$LOCAL_DIR_NAME" == *"/it/"* ]]; then
        LANG="it"
    elif [[ "$LOCAL_DIR_NAME" == *"/ja/"* ]]; then
        LANG="jp"
    elif [[ "$LOCAL_DIR_NAME" == *"/ko/"* ]]; then
        LANG="ko"
    elif [[ "$LOCAL_DIR_NAME" == *"/pt-BR/"* ]]; then
        LANG="pt"
    elif [[ "$LOCAL_DIR_NAME" == *"/ru/"* ]]; then
        LANG="ru"
    elif [[ "$LOCAL_DIR_NAME" == *"/zh-CN/"* ]]; then
        LANG="zh-cn"
    elif [[ "$LOCAL_DIR_NAME" == *"/zh-TW/"* ]]; then
        LANG="zh-tw"
    fi

    FILE_EXTENSION="${FILENAME##*.}"
    BASE_FILE_NAME="${FILENAME%.*}"

    TARGET_FILE_NAME="$BASE_FILE_NAME"

    if [[ -n "$LANG" ]]; then
        TARGET_FILE_NAME="$TARGET_FILE_NAME.$LANG"
        TARGET_FILE_NAME="$TARGET_FILE_NAME.$FILE_EXTENSION"
        cp "$LOCAL_DIR_NAME/$FILENAME" "$TARGET_DIR/$TARGET_FILE_NAME"
    fi

done 9< <( find $SOURCE_DIR -type f -exec printf '%s\0' {} + )

