#!/usr/bin/env fish

function update -d 'Update git repo'
  git stash --quiet 2>/dev/null
  git pull 2>/dev/null
  git stash apply --quiet 2>/dev/null
end

pushd $HOME/git/
for dir in ./*/
  cd $dir
  git status -sb 2>/dev/null
  if [ $status -eq 0 ]
    set_color red
    echo "
    Updating $dir...
    "
    set_color normal
    update
  end
  cd ..
end
popd
