#!/usr/bin/env bash

RED='\033[0;31m'
NC='\033[0m' # No Color

function update {
  git stash --quiet 2>/dev/null
  git pull 2>/dev/null
  git stash apply --quiet 2>/dev/null
}

pushd $HOME/git/
for dir in ./*/; do
  cd "$dir"
  git status -sb 2>/dev/null
  if [[ $status -eq 0 ]]; then
    printf "\n${RED}Updating $dir...${NC}"
    update
  fi
  cd ..
done
popd
