#!/usr/bin/env bash

PROJECT_PATH=`git config --get remote.origin.url | sed 's/^ssh.*@[^/]*\(\/.*\).git/\1/g'`

CURRENT_BRANCH_NAME="$(git branch --show-current)"
GITLAB_MR_URL="$GITLAB_BASE_URL$PROJECT_PATH/-/merge_requests/new?merge_request%5Bsource_branch%5D=$CURRENT_BRANCH_NAME"
git web--browse "$GITLAB_MR_URL"
