{ pkgs, lib, ... }: {
  nix = {
    package = lib.mkDefault pkgs.nix;
    trustedUsers = [ "mat" ];
    extraOptions = ''
      keep-outputs = true
      keep-derivations = true
      auto-optimise-store = true
      experimental-features = nix-command flakes
    '';
  };

  environment.systemPackages = [ pkgs.mullvad-vpn ];
  # going to use pipewire instead
  hardware.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services = {
    mullvad-vpn.enable = true;

    # Configure keymap in X11
    xserver = {
      xkb = {
        layout = "us";
        variant = "";
      };
    };

    # Enable CUPS to print documents.
    printing.enable = true;
    pipewire = {
      enable = true;
      alsa.enable = true;
      alsa.support32Bit = true;
      pulse.enable = true;
      # If you want to use JACK applications, uncomment this
      #jack.enable = true;

      # use the example session manager (no others are packaged yet so this is enabled by default,
      # no need to redefine it in your config for now)
      #media-session.enable = true;
    };
  };

  boot = {
    loader = {
      # bootloader
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };
  };

  systemd.extraConfig = ''
    DefaultTimeoutStopSec=10s
  '';
  systemd.user.extraConfig = ''
    DefaultTimeoutStopSec=10s
  '';

  networking = {
    wireguard.enable = true;
    networkmanager.enable = true;
    firewall.enable = true;
  };

  security = {
    sudo.enable = true;
    pam = {
      sshAgentAuth.enable = true;
      # sshAgentAuth.authorizedKeysFiles =
      #   lib.mkForce [ "/etc/ssh/authorized_keys.d/%u" ];
      services.sudo.sshAgentAuth = true;
    };
  };

  # Set your time zone.
  time.timeZone = "America/New_York";

  # Select internationalisation properties.
  i18n.defaultLocale = "en_US.UTF-8";

  i18n.extraLocaleSettings = {
    LC_ADDRESS = "en_US.UTF-8";
    LC_IDENTIFICATION = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_NAME = "en_US.UTF-8";
    LC_NUMERIC = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_TELEPHONE = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
  };

  users = {
    mutableUsers = false;
    users = {
      mat = {
        shell = pkgs.fish;
        isNormalUser = true;
        # generated by `mkpasswd`
        hashedPassword =
          "$y$j9T$L.RrmE3CRSB.lQayiw2ZN/$vA4XkSR13yL016t3HaZ11uCN/sCmXqBcuUcSBxMjiPD";
        home = "/home/mat";
        extraGroups = [
          "wheel"
          "networkmanager"
          "oci"
          "podman"
          "dialout" # to connect to arduino
        ];
        openssh.authorizedKeys.keys = [
          "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDsT6GLG7sY8YKX7JM+jqS3EAti3YMzwHKWViveqkZvu"
        ];
      };
    };
  };
}

