require('disable-builtins')
require('settings')
require('keybinds')
require('custom-filetypes')
require('configure-trailing-whitespace')
require('configure-plugins-generic')
require('lsp-init')
require('plugins')
