name: Build All Flake Outputs & Push to Cachix
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  build-and-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: wimpysworld/nothing-but-nix@main
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            download-buffer-size = 268435456
            accept-flake-config = true
      - uses: cachix/cachix-action@v16
        with:
          name: mrjones2014-dotfiles
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build all configurations
        run: |
          nix --accept-flake-config develop .#ci --command nix-fast-build --eval-workers 1 --skip-cached --no-nom --systems x86_64-linux,aarch64-darwin
          # track how much disk space the action uses
          df -h
